import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "AUTO ÉCOLE KIRAMA - Permis de conduire à Casablanca",
  keywords: [
    "auto-école",
    "permis de conduire",
    "permis B",
    "permis A",     
    "permis C",
    "formation conduite",
    "auto-école Casablanca",
    "inscription en ligne",
    "moniteurs professionnels",
    "formation rapide", 
    "taux de réussite",
    "conduite accompagnée",
    "formation théorique",
    "formation pratique", 
    "annexes auto-école",
    "Kiram",  
  ],
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
  


